// ==UserScript==
// @author                      Pawel Raszewski
// @email                       raszewski@gmail.com
// @name                        Eliminator Slajdow
// @namespace                   Eliminator Slajdow
// @description                 Eliminuje slajdy na stronach Agory
// @version                     @@version
// @grant                       none
// @icon                        http://eliminator-slajdow.herokuapp.com/assets/images/es_logo.svg
// @updateURL                   https://raw.githubusercontent.com/maestr0/eliminator-slajdow-chrome/master/userscript/eliminator-slajdow.user.js

// @include       http://autotrader.pl/*
// @include       http://*.autotrader.pl/*
// @include       http://avanti24.pl/*
// @include       http://*.avanti24.pl/*
// @include       http://groszki.pl/*
// @include       http://*.groszki.pl/*
// @include       http://ugotuj.to/*
// @include       http://*.ugotuj.to/*
// @include       http://gazeta.pl/*
// @include       http://*.gazeta.pl/*
// @include       http://tokfm.pl/*
// @include       http://*.tokfm.pl/*
// @include       http://gazetapraca.pl/*
// @include       http://*.gazetapraca.pl/*
// @include       http://moto.pl/*
// @include       http://*.moto.pl/*
// @include       http://plotek.pl/*
// @include       http://*.plotek.pl/*
// @include       http://deser.pl/*
// @include       http://*.deser.pl/*
// @include       http://demotywatory.pl/*
// @include       http://*.demotywatory.pl/*
// @include       http://sport.pl/*
// @include       http://*.sport.pl/*
// @include       http://wyborcza.pl/*
// @include       http://*.wyborcza.pl/*
// @include       http://gazetadom.pl/*
// @include       http://*.gazetadom.pl/*
// @include       http://logo24.pl/*
// @include       http://*.logo24.pl/*
// @include       http://wyborcza.biz/*
// @include       http://*.wyborcza.biz/*
// @include       http://lula.pl/*
// @include       http://*.lula.pl/*
// @include       http://naszemiasto.pl/*
// @include       http://*.naszemiasto.pl/*
// @include       http://tuba.pl/*
// @include       http://*.tuba.pl/*
// @include       http://edziecko.pl/*
// @include       http://*.edziecko.pl/*
// @include       http://czterykaty.pl/*
// @include       http://*.czterykaty.pl/*
// @include       http://alert24.pl/*
// @include       http://*.alert24.pl/*
// @include       http://kotek.pl/*
// @include       http://*.kotek.pl/*
// @include       http://polygamia.pl/*
// @include       http://*.polygamia.pl/*
// @include       http://popcorner.pl/*
// @include       http://*.popcorner.pl/*
// @include       http://wysokieobcasy.pl/*
// @include       http://*.wysokieobcasy.pl/*
// @include       http://e-ogrody.pl/*
// @include       http://*.e-ogrody.pl/*
// @include       http://ladnydom.pl/*
// @include       http://*.ladnydom.pl/*
// @include       http://bryla.gazetadom.pl/*
// @include       http://*.bryla.gazetadom.pl/*
// @include       http://metropraca.pl/*
// @include       http://*.metropraca.pl/*
// @include       http://pracawbiurze.pl/*
// @include       http://*.pracawbiurze.pl/*
// @include       http://zczuba.pl/*
// @include       http://*.zczuba.pl/*
// @include       http://ciacha.net/*
// @include       http://*.ciacha.net/*
// @include       http://biznes.pl/*
// @include       http://*.biznes.pl/*
// @include       http://namonciaku.pl/*
// @include       http://*.namonciaku.pl/*
// @include       http://magazyn-kuchnia.pl/*
// @include       http://*.magazyn-kuchnia.pl/*
// @include       http://swiatmotocykli.pl/*
// @include       http://*.swiatmotocykli.pl/*
// @include       http://domosfera.pl/*
// @include       http://*.domosfera.pl/*
// @include       http://bryla.pl/*
// @include       http://*.bryla.pl/*
// @include       http://domiwnetrze.pl/*
// @include       http://*.domiwnetrze.pl/*
// @include       http://onet.pl/*
// @include       http://*.onet.pl/*
// @include       http://gazetalubuska.pl/*
// @include       http://*.gazetalubuska.pl/*
// @include       http://dziennikwschodni.pl/*
// @include       http://*.dziennikwschodni.pl/*
// @include       http://echodnia.eu/*
// @include       http://*.echodnia.eu/*
// @include       http://pomorska.pl/*
// @include       http://*.pomorska.pl/*
// @include       http://wspolczesna.pl/*
// @include       http://*.wspolczesna.pl/*
// @include       http://gk24.pl/*
// @include       http://*.gk24.pl/*
// @include       http://gp24.pl/*
// @include       http://*.gp24.pl/*
// @include       http://gs24.pl/*
// @include       http://*.gs24.pl/*
// @include       http://poranny.pl/*
// @include       http://*.poranny.pl/*
// @include       http://nowiny24.pl/*
// @include       http://*.nowiny24.pl/*
// @include       http://nto.pl/*
// @include       http://*.nto.pl/*
// @include       http://to.com.pl/*
// @include       http://*.to.com.pl/*
// @include       http://mmbydgoszcz.pl/*
// @include       http://*.mmbydgoszcz.pl/*
// @include       http://mmwroclaw.pl/*
// @include       http://*.mmwroclaw.pl/*
// @include       http://mmkrakow.pl/*
// @include       http://*.mmkrakow.pl/*
// @include       http://mmlodz.pl/*
// @include       http://*.mmlodz.pl/*
// @include       http://mmlublin.pl/*
// @include       http://*.mmlublin.pl/*
// @include       http://mmpoznan.pl/*
// @include       http://*.mmpoznan.pl/*
// @include       http://mmsilesia.pl/*
// @include       http://*.mmsilesia.pl/*
// @include       http://mmszczecin.pl/*
// @include       http://*.mmszczecin.pl/*
// @include       http://mmtrojmiasto.pl/*
// @include       http://*.mmtrojmiasto.pl/*
// @include       http://mmwarszawa.pl/*
// @include       http://*.mmwarszawa.pl/*
// @include       http://mmmojemiasto.pl/*
// @include       http://*.mmmojemiasto.pl/*
// @include       http://mmopole.pl/*
// @include       http://*.mmopole.pl/*
// @include       http://mmzielonagora.pl/*
// @include       http://*.mmzielonagora.pl/*
// @include       http://foch.pl/*
// @include       http://*.foch.pl/*
// @include       http://edulandia.pl/*
// @include       http://*.edulandia.pl/*
// @include       http://wp.pl/*
// @include       http://*.wp.pl/*
// @include       http://kwejk.pl/*
// @include       http://*.kwejk.pl/*
// @include       http://gazetawroclawska.pl/*
// @include       http://*.gazetawroclawska.pl/*
// @include       http://polskatimes.pl/*
// @include       http://*.polskatimes.pl/*
// @include       http://dziennikbaltycki.pl/*
// @include       http://*.dziennikbaltycki.pl/*
// @include       http://dzienniklodzki.pl/*
// @include       http://*.dzienniklodzki.pl/*
// @include       http://dziennikpolski24.pl/*
// @include       http://*.dziennikpolski24.pl/*
// @include       http://dziennikzachodni.pl/*
// @include       http://*.dziennikzachodni.pl/*
// @include       http://expressilustrowany.pl/*
// @include       http://*.expressilustrowany.pl/*
// @include       http://gazetakrakowska.pl/*
// @include       http://*.gazetakrakowska.pl/*
// @include       http://gloswielkopolski.pl/*
// @include       http://*.gloswielkopolski.pl/*
// @include       http://kurierlubelski.pl/*
// @include       http://*.kurierlubelski.pl/*
// @include       http://fakt.pl/*
// @include       http://*.fakt.pl/*
// @include       http://wawalove.pl/*
// @include       http://*.wawalove.pl/*
// @include       http://www.se.pl/*
// @include       http://*.www.se.pl/*
// @include       http://sfora.pl/*
// @include       http://*.sfora.pl/*
// @include       http://biztok.pl/*
// @include       http://*.biztok.pl/*
// @include       http://komputerswiat.pl/*
// @include       http://*.komputerswiat.pl/*
// @include       http://dziennik.pl/*
// @include       http://*.dziennik.pl/*
// @include       http://jegostrona.pl/*
// @include       http://*.jegostrona.pl/*
// @include       http://forsal.pl/*
// @include       http://*.forsal.pl/*
// @include       http://wprzerwie.pl/*
// @include       http://*.wprzerwie.pl/*
// @include       http://przegladsportowy.pl/*
// @include       http://*.przegladsportowy.pl/*
// @include       http://auto-swiat.pl/*
// @include       http://*.auto-swiat.pl/*
// @include       http://sportowefakty.pl/*
// @include       http://*.sportowefakty.pl/*
// @include       http://motokiller.pl/*
// @include       http://*.motokiller.pl/*
// @include       http://bebzol.com/*
// @include       http://*.bebzol.com/*
// @include       http://lovekrakow.pl/*
// @include       http://*.lovekrakow.pl/*
// @include       http://pudelekx.pl/*
// @include       http://*.pudelekx.pl/*
// @include       http://urzadzamy.pl/*
// @include       http://*.urzadzamy.pl/*
// @include       http://snobka.pl/*
// @include       http://*.snobka.pl/*
// @include       http://fly4free.pl/*
// @include       http://*.fly4free.pl/*
// @include       http://gadzetomania.pl/*
// @include       http://*.gadzetomania.pl/*
// @include       http://trojmiasto.pl/*
// @include       http://*.trojmiasto.pl/*
// @include       http://regiomoto.pl/*
// @include       http://*.regiomoto.pl/*
// @include       http://sportfan.pl/*
// @include       http://*.sportfan.pl/*
// @include       http://forbes.pl/*
// @include       http://*.forbes.pl/*
// @include       http://geekweek.pl/*
// @include       http://*.geekweek.pl/*
// @include       http://eliminator-slajdow.herokuapp.com/*
// @include       http://*.eliminator-slajdow.herokuapp.com/*
// @include       http://nocoty.pl/*
// @include       http://*.nocoty.pl/*
// @include       http://domiporta.pl/*
// @include       http://*.domiporta.pl/*
// @include       http://newsweek.pl/*
// @include       http://*.newsweek.pl/*

// ==/UserScript==